export const UPDATE_APP_STATE_FROM_STORAGE = 'UPDATE_APP_STATE_FROM_STORAGE';

export const FETCH_IMAGES_START = 'FETCH_IMAGES_START';
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS';
export const FETCH_IMAGES_ERROR = 'FETCH_IMAGES_ERROR';

export const FAV_IMAGE = 'FAV_IMAGE';
export const UNFAV_IMAGE = 'UNFAV_IMAGE';
export const TOGGLE_FAV_IMAGE = 'TOGGLE_FAV_IMAGE';

export const RM_IMAGE = 'RM_IMAGE';
